baseURL: //www.madebymice.com/
languageCode: en-us
title: Made by Mice - The portfolio of Raf Van Suetendael
params:
  author: Raf Van Suetendael
  description: Web- / Graphic- and interactive design made by mice.

theme: madebymice