baseURL: //www.madebymice.com/
languageCode: en-us
title: Portfolio of Raf Van Suetendael
params:
  author: Raf Van Suetendael
  description: Web- / Graphic- and interactive design by Raf Van Suetendael.

theme: madebymice